version: '2'
services:
  135026-traefik:
    image: traefik
    command: -c /dev/null --web --docker --docker.domain=dck.mojserver.mk
    labels:
      - "traefik.enable=false"
    ports:
      - "17000:80"
      - "17080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  135026-eureka:
    image: 135026_dockerhub_user/task5-eureka
    labels:
      - "traefik.port=8761"
      - "traefik.backend=135026-eureka"
      - "traefik.frontend.rule=Host:135026-eureka.dck.mojserver.mk"
    expose:
      - "8761"
    ports:
      - "8761:8761"

  135026-mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbp4ss
      MYSQL_DATABASE: demo
    volumes:
      - 135026-datavolume:/var/lib/mysql
    labels:
      - "traefik.enable=false"

  135026-app:
    image: 135026_dockerhub_user/task5-app
    labels:
      - "traefik.port=8080"
      - "traefik.backend=135026-app"
      - "traefik.frontend.rule=Host:135026-app.dck.mojserver.mk"
    links:
      - 135026-mysql
      - 135026-eureka
    depends_on:
      - 135026-mysql
      - 135026-traefik
      - 135026-eureka

volumes:
  135026-datavolume: {}
